// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztrvvwusjzbmkvmbymhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cnZ2d3VzanpibWt2bWJ5bWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTI0OTgsImV4cCI6MjA2MTMyODQ5OH0.m65RJDWnpBhChvdmM6yjdrY9_Mgk8sUw9Ij8XzNo6SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);